# SPDX-FileCopyrightText: 2025 Lukas Winkler
#
# SPDX-License-Identifier: AGPL-3.0-or-later

server:
  host: localhost
  port: 8943
  data_attribution_link: "https://about.route.lw1.at"


osm: datasets/austria-latest.osm.pbf
tiles:
  profile: custom-tile-profile.lua
  db_size: 274877906944
  flush_threshold: 100000
timetable:
  first_day: -30
  num_days: 395
  tb: false
  railviz: true
  with_shapes: true
  route_shapes:
    clasz:
      COACH: false
    mode: all
    debug_api: true
  adjust_footpaths: true
  merge_dupes_intra_src: false
  merge_dupes_inter_src: false
  link_stop_distance: 200
  update_interval: 60
  http_timeout: 30
  incremental_rt_update: false
  use_osm_stop_coordinates: false
  extend_missing_footpaths: false
  max_footpath_length: 25
  max_matching_distance: 25.000000
  preprocess_max_matching_distance: 250
  datasets:
    00-eisenbahn:
      path: datasets/gtfs/00_eisenbahn.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    ferries:
      path: own_gtfs/gtfs_output/donau_fähren.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
    01-linz:
      path: datasets/gtfs/01_linz.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    02-ooe:
      path: datasets/gtfs/02_ooe.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    03-salzburg:
      path: datasets/gtfs/03_salzburg.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    04-kaernten:
      path: datasets/gtfs/04_kaernten.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
      default_timezone: Europe/Vienna
    05-vor:
      path: datasets/gtfs/05_vor.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
      rt:
        - url: https://unofficial-gtfsrt-proxy.route.lw1.at/vienna-gtfs-rt.pb
    06-steiermark:
      path: datasets/gtfs/06_steiermark.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    07-tirol:
      path: datasets/gtfs/07_tirol.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    08-vorarlberg:
      path: datasets/gtfs/08_vorarlberg.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/colors.lua
    flixbus-gtfs-generic-eu:
      path: datasets/flixbus_gtfs_generic_eu.zip
      default_bikes_allowed: false
      default_cars_allowed: false
      extend_calendar: false
      script: scripts/eu-flixbus.lua

elevators: false
osr_footpath: true
geocoding: true
reverse_geocoding: true

street_routing:
  elevation_data_dir: ./datasets/hgt

### Start GBFS
gbfs:
  feeds:
    bird_wiener_neustadt:
      url: https://mds.bird.co/gbfs/v2/public/wienerneustadt/gbfs.json
    dott_baden_bei_wien:
      url: https://gbfs.api.ridedott.com/public/v2/baden-bei-wien/gbfs.json
    dott_bregenz:
      url: https://gbfs.api.ridedott.com/public/v2/bregenz/gbfs.json
    dott_dornbirn:
      url: https://gbfs.api.ridedott.com/public/v2/dornbirn/gbfs.json
    dott_feldkirchen_bei_graz:
      url: https://gbfs.api.ridedott.com/public/v2/feldkirchen-bei-graz/gbfs.json
    dott_innsbruck:
      url: https://gbfs.api.ridedott.com/public/v2/innsbruck/gbfs.json
    dott_klagenfurt:
      url: https://gbfs.api.ridedott.com/public/v2/klagenfurt/gbfs.json
    dott_klopein:
      url: https://gbfs.api.ridedott.com/public/v2/klopein/gbfs.json
    dott_korneuburg:
      url: https://gbfs.api.ridedott.com/public/v2/korneuburg/gbfs.json
    dott_leoben:
      url: https://gbfs.api.ridedott.com/public/v2/leoben/gbfs.json
    dott_linz:
      url: https://gbfs.api.ridedott.com/public/v2/linz/gbfs.json
    dott_modling:
      url: https://gbfs.api.ridedott.com/public/v2/modling/gbfs.json
    dott_sankt_anton_am_arlberg:
      url: https://gbfs.api.ridedott.com/public/v2/sankt-anton-am-arlberg/gbfs.json
    dott_serfaus:
      url: https://gbfs.api.ridedott.com/public/v2/serfaus/gbfs.json
    dott_steyr:
      url: https://gbfs.api.ridedott.com/public/v2/steyr/gbfs.json
    dott_velden_am_worthersee:
      url: https://gbfs.api.ridedott.com/public/v2/velden-am-worthersee/gbfs.json
    dott_villach:
      url: https://gbfs.api.ridedott.com/public/v2/villach/gbfs.json
    dott_wels:
      url: https://gbfs.api.ridedott.com/public/v2/wels/gbfs.json
    nextbike_al:
      url: https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_al/gbfs.json
    nextbike_eq:
      url: https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_eq/gbfs.json
    nextbike_ka:
      url: https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_ka/gbfs.json
    nextbike_la:
      url: https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_la/gbfs.json
    nextbike_si:
      url: https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_si/gbfs.json
    nextbike_vt:
      url: https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_vt/gbfs.json
    nextbike_wr:
      url: https://gbfs.nextbike.net/maps/gbfs/v2/nextbike_wr/gbfs.json
### End GBFS

limits:
  stoptimes_max_results: 16384
  plan_max_results: 256
  plan_max_search_window_minutes: 5760
  stops_max_results: 2048
  onetoall_max_results: 524288
  onetoall_max_travel_minutes: 2880
  routing_max_timeout_seconds: 90
