from enum import Enum


class AlertCause(str, Enum):
    ACCIDENT = "ACCIDENT"
    CONSTRUCTION = "CONSTRUCTION"
    DEMONSTRATION = "DEMONSTRATION"
    HOLIDAY = "HOLIDAY"
    MAINTENANCE = "MAINTENANCE"
    MEDICAL_EMERGENCY = "MEDICAL_EMERGENCY"
    OTHER_CAUSE = "OTHER_CAUSE"
    POLICE_ACTIVITY = "POLICE_ACTIVITY"
    SPECIAL_EVENT = "SPECIAL_EVENT"
    STRIKE = "STRIKE"
    TECHNICAL_PROBLEM = "TECHNICAL_PROBLEM"
    UNKNOWN_CAUSE = "UNKNOWN_CAUSE"
    WEATHER = "WEATHER"

    def __str__(self) -> str:
        return str(self.value)
