from enum import Enum


class Mode(str, Enum):
    AERIAL_LIFT = "AERIAL_LIFT"
    AIRPLANE = "AIRPLANE"
    AREAL_LIFT = "AREAL_LIFT"
    BIKE = "BIKE"
    BUS = "BUS"
    CABLE_CAR = "CABLE_CAR"
    CAR = "CAR"
    CAR_DROPOFF = "CAR_DROPOFF"
    CAR_PARKING = "CAR_PARKING"
    COACH = "COACH"
    DEBUG_BUS_ROUTE = "DEBUG_BUS_ROUTE"
    DEBUG_FERRY_ROUTE = "DEBUG_FERRY_ROUTE"
    DEBUG_RAILWAY_ROUTE = "DEBUG_RAILWAY_ROUTE"
    FERRY = "FERRY"
    FLEX = "FLEX"
    FUNICULAR = "FUNICULAR"
    HIGHSPEED_RAIL = "HIGHSPEED_RAIL"
    LONG_DISTANCE = "LONG_DISTANCE"
    METRO = "METRO"
    NIGHT_RAIL = "NIGHT_RAIL"
    ODM = "ODM"
    OTHER = "OTHER"
    RAIL = "RAIL"
    REGIONAL_FAST_RAIL = "REGIONAL_FAST_RAIL"
    REGIONAL_RAIL = "REGIONAL_RAIL"
    RENTAL = "RENTAL"
    RIDE_SHARING = "RIDE_SHARING"
    SUBURBAN = "SUBURBAN"
    SUBWAY = "SUBWAY"
    TRAM = "TRAM"
    TRANSIT = "TRANSIT"
    WALK = "WALK"

    def __str__(self) -> str:
        return str(self.value)
