"""
based on https://github.com/public-transport/transitous/blob/main/src/generate_colors.py
SPDX-FileCopyrightText: Lukas Winkler, Levin Baumann <github@17d.me>
SPDX-License-Identifier: AGPL-3.0-or-later
"""
from pathlib import Path


def _escape_lua_string(s: str) -> str:
    return s.replace('\\', '\\\\').replace('"', '\\"')


def write_lua_table(by_gtfs_id: dict[str, ...], target: Path):
    with target.open("w") as f:
        f.write('-- autogenerated by lua-export.py\n')
        f.write("-- SPDX-FileCopyrightText: OpenStreetMap\n")
        f.write("-- SPDX-License-Identifier: ODbL-1.0\n\n")
        f.write('local colors_by_id = {\n')

        for raw_id, info in by_gtfs_id.items():
            safe_id = _escape_lua_string(raw_id)
            bg = info["color"][1:]
            text = info["text_color"][1:]

            f.write(f'    ["{safe_id}"] = {{ color = 0x{bg}, text_color = 0x{text} }},\n')
        f.write('}\n')

        f.write("return colors_by_id")
